- name: instalando o servidor web
  package:
   name: "{{ item.nome }}"
  when: ansible_os_family == item.distro
  with_items:
    - { nome: apache2, distro: "Debian" }
    - { nome: httpd, distro: "Redhat" }
  notify: start_centos
